### ISSUE TITLE
Update PyPi please?

### ISSUE THREAD

**Issue by lurch** [lucasdemarchi/codespell#101]
The version of [codespell on pypi](https://pypi.python.org/pypi/codespell) is 1.9.2, which is almost 9 months old (and doesn't have support for loading multiple dictionaries).

Could we have a new release please? :-)

**Comment by lucasdemarchi** [comment]
@Eric89GXL didn't you do a release on january? (https://github.com/lucasdemarchi/codespell/pull/96#discussion_r95050463)

**Comment by Eric89GXL** [comment]
Oof, no. I think I meant to but it didn't happen. Should I go for it now?

**Comment by lucasdemarchi** [comment]
Yes, please. It can be 1.10. Thanks.

**Comment by Eric89GXL** [comment]
Alright, I should be able to do it early next week. If I don't, feel free to send an angry ping my way.

**Comment by Eric89GXL** [comment]
https://pypi.python.org/pypi/codespell/1.10.0

**Comment by lurch** [comment]
Thank you :-)
