### ISSUE TITLE
What does 'disable due to \n' mean? 

### ISSUE THREAD

**Issue by luzpaz** [lucasdemarchi/codespell#111]
Codespell result looked like: 
`./App/AreaPyImp.cpp:163: nTo  ==> not  | disable due to \n`

The code in question:
```
"\nTo ensure no stray abortion is left in the previous operation, it is advised to manually clear\n"
```

**Comment by ge-fa** [comment]
Ping..

**Comment by larsoner** [comment]
It means that the potential error is preceded by `\n` so it is ignored. It is a disambiguation problem regarding whether there is a `\n` followed by `To`, or a `\` followed by a typo `nTo`. To be safe it's assumed it's a `\n` and thus ignored.
