### ISSUE TITLE
Would it be possible to release a new minor version?

### ISSUE THREAD

**Issue by luzpaz** [lucasdemarchi/codespell#115]
So as to include the bdc95edd79459c88d9b45e860e415750b31c33e8 and other dictionary additions ?

**Comment by lucasdemarchi** [comment]
I'd like to fix #108  first. I have a partial solution, but I need to give it some more testing.

**Comment by lucasdemarchi** [comment]
I tried some quick changes for #108, but I don't think I'll be able to commit time to it soon. Maybe we can do a release, yes.

**Comment by lucasdemarchi** [comment]
@larsoner could you do it?

**Comment by larsoner** [comment]
I can hopefully do it in the next week or so

**Comment by luzpaz** [comment]
may I ask that the remaining PRs be merged before new release takes place ?

**Comment by luzpaz** [comment]
all relevant remaining PRs have been merged. Green light 👍 😀

**Comment by luzpaz** [comment]
@larsoner any open availability to release a new minor version ?

**Comment by larsoner** [comment]
Not at the moment, hopefully soon

**Comment by larsoner** [comment]
Should be doable after #136 lands

**Comment by luzpaz** [comment]
#136 has been merged 😄

**Comment by larsoner** [comment]
1.11.0:

https://pypi.python.org/pypi/codespell/
