### ISSUE TITLE
Integrate QGIS spelling.dat list entries in to dictionary.txt

### ISSUE THREAD

**Issue by luzpaz** [lucasdemarchi/codespell#135]
[QGIS](http://github.com/QGIS/QGIS) has a typo detection tool in their repo with a list that they have created for well known typos. It lives at: https://github.com/qgis/QGIS/blob/master/scripts/spell_check/spelling.dat
Notice though they do prefer British English spelling. 

I was trying to write a script that would diff out all non-duplicate entries so I could add them to codespell. But I've been hitting snags so I opened up this issue.

**Comment by thdot** [comment]
That looks very interesting.
Do we have a licence problem when we integrate the database? QGIS is published under the GPL.
