### ISSUE TITLE
How to use codespell to test a project's incoming PRs via Continuous Integration (ex. TravisCI)

### ISSUE THREAD

**Issue by luzpaz** [lucasdemarchi/codespell#139]
Has anyone seen or used codespell as a unit test that gets triggered in TravisCI when a new PR submitted ?

Downstream ticket: https://freecadweb.org/tracker/view.php?id=3205

**Comment by luzpaz** [comment]
Found https://blog.eleven-labs.com/en/how-to-check-the-spelling-of-your-docs-from-travis-ci/

**Comment by larsoner** [comment]
We use it here:

https://github.com/mne-tools/mne-python/blob/master/.travis.yml#L173

And the Makefile (`make codespell` for interactive mode and `make codespell-error` for CI):

https://github.com/mne-tools/mne-python/blob/master/Makefile#L99

**Comment by luzpaz** [comment]
Cool! Perhaps we can flesh this out in to a guide on the wiki ?

**Comment by luzpaz** [comment]
@larsoner Looks like it's possible to notify submitter of the results using a github token. Does mne-tools/mne-python do this ?

```
curl -i -H "Authorization: token $GITHUB_TOKEN" \
    -H "Content-Type: application/json" \
    -X POST -d "{\"body\":\"$ASPELL_RESULTS\"}" \
    https://api.github.com/repos/eleven-labs/eleven-labs.github.io/issues/$TRAVIS_PULL_REQUEST/comments
```

**Comment by larsoner** [comment]
No we don't bother, just let the red CI status lead them to check. But it sounds potentially useful.

**Comment by luzpaz** [comment]
Lets keep this is open while I study this, larsoner. Then I'll write a short tut on how to integrate it and add it to the README.

**Comment by luzpaz** [comment]
My progress: https://gist.github.com/luzpaz/76c7cbbb7edcb916f1ce69a14453478a

**Comment by luzpaz** [comment]
Here is how you tell codespell to run on all changed files in a submitted PR:
```
mapfile -t files < <(git diff --name-only $TRAVIS_COMMIT_RANGE); codespell -d -q 3 -S "$CODESPELL_SKIPS" -I ./whitelist.txt  "${files[@]}"
```

**Comment by larsoner** [comment]
Closing as solved

**Comment by luzpaz** [comment]
Folks over at numpy have another solution: https://github.com/numpy/numpy/issues/13694
