### ISSUE TITLE
How to install the most bleeding edge version of codespell via apt-get ?

### ISSUE THREAD

**Issue by luzpaz** [lucasdemarchi/codespell#157]
Context #139 
I'm wanting to install the most up to date dev version of codespell via apt-get. I want this because in the travisci sequence `addon:` is [the first](https://docs.travis-ci.com/user/customizing-the-build#The-Build-Lifecycle). 
I'd like to run the equivalent of `pip3 install --user --upgrade git+https://github.com/lucasdemarchi/codespell.git` as an `apt-get` command...how do I do this?

**Comment by larsoner** [comment]
`apt-get` is a system package manager, not a Python package manager, you can't get `apt-get` to do this AFAIK
