### ISSUE TITLE
proposal: remove or assign lower visibility to `iff`

### ISSUE THREAD

**Issue by luzpaz** [lucasdemarchi/codespell#163]
Currently codespell dictionary.txt has `iff->if` as an entry. 
Iff in mathematics means `if and only if` see https://en.wikipedia.org/wiki/iff
I get a ton of false positives with it. 
I suggest we to either remove it or designate it as 
`iff->if, disabled due to a valid mathematical concept` or something...
Thoughts?

**Comment by larsoner** [comment]
I'm fine with that
