### ISSUE TITLE
proposal: proposal: remove or assign lower visibility to `dum`

### ISSUE THREAD

**Issue by luzpaz** [lucasdemarchi/codespell#167]
I get a lot of false positives with `dum` over multiple FOSS projects. I say we get rid of it or do the same as we did in #163 
Thoughts?

**Comment by larsoner** [comment]
Where is this used?

**Comment by luzpaz** [comment]
@larsoner FreeCAD, cython, opencascade to name a few

**Comment by larsoner** [comment]
This gives me no results?

https://github.com/cython/cython/search?utf8=%E2%9C%93&q=dum&type=

**Comment by luzpaz** [comment]
my mistake, it wasn't `cython` ... but here are some other examples: 

https://github.com/FreeCAD/FreeCAD/search?utf8=%E2%9C%93&q=dum&type=
https://github.com/3drepo/occt/search?utf8=%E2%9C%93&q=dum&type=
https://github.com/Kitware/VTK/search?utf8=%E2%9C%93&q=dum&type=
https://github.com/ElmerCSC/elmerfem/search?utf8=%E2%9C%93&q=dum&type=
https://github.com/FedoraScientific/salome-smesh/search?utf8=%E2%9C%93&q=dum&type=

**Comment by larsoner** [comment]
We have to choose between false positives for `dum` in these projects and false negatives from removing `dum`. In this case I'd vote for letting those projects use the ignore directives

**Comment by luzpaz** [comment]
fair enough 👍
