### ISSUE TITLE
manpage

### ISSUE THREAD

**Issue by cinemast** [lucasdemarchi/codespell#25]
Hi Lucas!

Thank you for providing codespell, I use it almost every day.

I recognized that there is no manpage for this tool. It would be nice to have one. However Paul Wise hinted that there might occur inconsistencies between the manpage and the --help option.

See here: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=779900

What do you think about adding a `git help` like approach for --help and the manpage?

Greetings
Peter

**Comment by lucasdemarchi** [comment]
I'm ok with it.

**Comment by anatol** [comment]
+1 More documentation is better. @cinemast, please send a pull request.

**Comment by jwilk** [comment]
I'm all for adding a manpage, but please don't make --help spawn man.

When I run `foo --help` I want it to display a short list of options and their descriptions, not a full-fledged manpage.

**Comment by cinemast** [comment]
I think we can close this issue now.
