### ISSUE TITLE
Where in the documentation does it say Python 3 is a requirement?

### ISSUE THREAD

**Issue by uberhacker** [lucasdemarchi/codespell#29]
Please update README.md.  On a CentOS 6.6 system (python 2.6.6), I received the following message after attempting to execute codespell.py:

$ python codespell.py
  File "codespell.py", line 146
    file=sys.stderr)
        ^
SyntaxError: invalid syntax

$ ./codespell.py
/usr/bin/env: python3: No such file or directory

Also, in the Usage section, it should be './codespell.py -h' and not './codespell -h'.

**Comment by lucasdemarchi** [comment]
it's in the first line of the script where it says it wants python3 to run. A patch adding the requirements to the README file is welcome.
With enough effort it could be made compatible with python 2.7, but 2.6 is not possible.

**Comment by uberhacker** [comment]
Hi Lucas,
Thanks for the quick response.  This is a great project and I appreciate all the hard work that went into it.  I can certainly create a pull request for the updated README.md.
Thanks

**Comment by jwilk** [comment]
AFAICS, README was updated in d4ab1814, so this bug can be closed.

**Comment by lucasdemarchi** [comment]
Yep
