### ISSUE TITLE
Feature: CI test to sort any submitted corrections to dictionary.txt 

### ISSUE THREAD

**Issue by luzpaz** [lucasdemarchi/codespell#310]
As @pabs3 does from time to time manually, have this process automated.

**Comment by pabs3** [comment]
FYI the script I use for submitting spelling corrections automatically
sorts the dictionary and commits that before committing my changes,
so it is not a problem for me if the dictionary isn't sorted sometimes.

**Comment by luzpaz** [comment]
@pabs3 can you share the logic of how you sort it ?

**Comment by pabs3** [comment]
I just run the existing Makefile target:

make sort-dictionary
