### ISSUE TITLE
Codespell should ignore empty files (and not print error/warning).

### ISSUE THREAD

**Issue by qeny** [lucasdemarchi/codespell#34]
One minor change in behavior that could be made: Right now, if a file is empty it prints something like:

`ERROR: Could not detect encoding: ./__init__.py`

It should probably just pass over these files and not print anything.

**Comment by lucasdemarchi** [comment]
Are you using codespell from master? I remember this was fixed some time ago

**Comment by qeny** [comment]
Agh, good point, I wasn't using it from master (I was just using the stable debian package version). Just tried latest version, and this is not an issue.
