### ISSUE TITLE
False positive with a unicode apostrophe

### ISSUE THREAD

**Issue by sylvestre** [lucasdemarchi/codespell#394]
with foo.xml containing:
`<!ENTITY unknownProtocolFound.title "The address wasn’t understood">
`
_$ codespell foo.xml_
`foo.xml:1: wasn  ==> wasn't, was`

**Comment by peternewman** [comment]
I think this is closed in https://github.com/lucasdemarchi/codespell/pull/418 . Or is this the other issue where the apostrophe means wasn is always matched, and is effectively a false positive?

**Comment by sylvestre** [comment]
Indeed, thanks!
