### ISSUE TITLE
Making the build reproducible 

### ISSUE THREAD

**Issue by ge-fa** [lucasdemarchi/codespell#419]
Hi all,

There is an effort in Debian to ensure packages do build reproducible. Currently, codespell does fail in this regard, because it includes a [path in the help output](https://github.com/lucasdemarchi/codespell/blob/master/codespell_lib/_codespell.py#L223) (and therefore in the manpage). There is a proposed patch in Debian which just disables embedding the path in the output -- but before applying it, I wanted to ask people over here: what do you think?

Also, I'm much more in favor of getting this fixed here, upstream, instead of in Debian, downstream.

Thanks for your work,
cheers,
Georg

**Comment by larsoner** [comment]
I'm fine with removing the actual path and saying that it's part of the package data instead

**Comment by ge-fa** [comment]
Great, should I send a patch for this?

**Comment by larsoner** [comment]
Yes please

**Comment by lamby** [comment]
Aww, no attribution? ;-)

**Comment by lamby** [comment]
@ge-fa No worries. Not a big deal for me, but it might put off others hence I mention it!
