### ISSUE TITLE
make install fails to create codespell from codespell.py

### ISSUE THREAD

**Issue by uberhacker** [lucasdemarchi/codespell#42]
make: *** [check-dictionary] Error 1

System specs:
Linux 3.2.0-4-amd64
Debian 7.8
Python 3.2.3-7

**Comment by anatol** [comment]
Provide full build log

**Comment by uberhacker** [comment]
$ sudo make install --debug=v
GNU Make 3.81
Copyright (C) 2006  Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.

This program built for x86_64-pc-linux-gnu
Reading makefiles...
Reading makefile `Makefile'...
Updating goal targets....
Considering target file `install'.
 File `install' does not exist.
  Considering target file `codespell'.
   File `codespell' does not exist.
    Considering target file `codespell.py'.
     Finished prerequisites of target file `codespell.py'.
    No need to remake target `codespell.py'.
    Considering target file `check-dictionary'.
     File `check-dictionary' does not exist.
     Finished prerequisites of target file `check-dictionary'.
    Must remake target `check-dictionary'.
sort: data/dictionary.txt:274: disorder: Amercia->America
Dictionary not sorted. Sort with 'make sort-dictionary'
make: *** [check-dictionary] Error 1

**Comment by anatol** [comment]
The answer to your question in your log

```
sort: data/dictionary.txt:274: disorder: Amercia->America
Dictionary not sorted. Sort with 'make sort-dictionary
```

**Comment by uberhacker** [comment]
That doesn't fix it either.

$ sudo make sort-dictionary
LANG=C sort -f -u -o data/dictionary.txt data/dictionary.txt

$ sudo make install
sort: data/dictionary.txt:274: disorder: Amercia->America
Dictionary not sorted. Sort with 'make sort-dictionary'
make: *** [check-dictionary] Error 1

**Comment by uberhacker** [comment]
OK, for what it's worth, I was able to create codespell from codespell.py by executing the following:

$ sort -f -u -o check-dictionary data/dictionary.txt

$ make install
