### ISSUE TITLE
make install fails to create codespell from codespell.py

### ISSUE THREAD

**Issue by uberhacker** [lucasdemarchi/codespell#43]
vagrant@debian:~/.codespell (master)$ make install
sort: data/dictionary.txt:274: disorder: Amercia->America
Dictionary not sorted. Sort with 'make sort-dictionary'
make: *** [check-dictionary] Error 1
vagrant@debian:~/.codespell (master)$ make sort-dictionary
LANG=C sort -f -u -o data/dictionary.txt data/dictionary.txt
vagrant@debian:~/.codespell (master)$ make install --debug=v
GNU Make 3.81
Copyright (C) 2006  Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.

This program built for x86_64-pc-linux-gnu
Reading makefiles...
Reading makefile `Makefile'...
Updating goal targets....
Considering target file `install'.
 File `install' does not exist.
  Considering target file `codespell'.
   File `codespell' does not exist.
    Considering target file `codespell.py'.
     Finished prerequisites of target file `codespell.py'.
    No need to remake target `codespell.py'.
    Considering target file `check-dictionary'.
     File `check-dictionary' does not exist.
     Finished prerequisites of target file `check-dictionary'.
    Must remake target `check-dictionary'.
sort: data/dictionary.txt:274: disorder: Amercia->America
Dictionary not sorted. Sort with 'make sort-dictionary'
make: *** [check-dictionary] Error 1
vagrant@debian:~/.codespell (master)$ ./codespell
-bash: ./codespell: No such file or directory
vagrant@debian:~/.codespell (master)$ ls -lA
total 72
-rw-r--r-- 1 vagrant vagrant   439 Sep  9 21:25 codespell.1.include
-rwxr-xr-x 1 vagrant vagrant 17900 Sep  9 21:25 codespell.py
-rw-r--r-- 1 vagrant vagrant 18092 Sep  9 21:25 COPYING
drwxr-xr-x 2 vagrant vagrant  4096 Sep  9 21:25 data
drwxr-xr-x 2 vagrant vagrant  4096 Sep  9 21:25 example
drwxr-xr-x 8 vagrant vagrant  4096 Sep  9 21:26 .git
-rw-r--r-- 1 vagrant vagrant  2223 Sep  9 21:25 Makefile
-rw-r--r-- 1 vagrant vagrant   294 Sep  9 21:25 NEWS
-rw-r--r-- 1 vagrant vagrant  3035 Sep  9 21:25 README.md
-rw-r--r-- 1 vagrant vagrant   107 Sep  9 21:25 TODO

**Comment by Eric89GXL** [comment]
Should hopefully be fixed with latest install steps
