### ISSUE TITLE
Update README to reflect requirement for Python 3. 

### ISSUE THREAD

**Issue by gtmills** [lucasdemarchi/codespell#441]
From https://github.com/lucasdemarchi/codespell/blob/master/README.rst
```
Requirements
Python 2.7 or above.
```

but codespell requires Python3.
https://github.com/lucasdemarchi/codespell/blob/master/bin/codespell#L1

**Comment by larsoner** [comment]
In practice when installed a standard way (e.g., via `pip install` or `python setup.py ...`) this should not be the case. Are you having issues with Python2?

**Comment by gtmills** [comment]
When using bin/codespell:
```
/usr/bin/env: python3: No such file or directory
```
If python3 is a requirement please document it. 
I am able to change https://github.com/lucasdemarchi/codespell/blob/master/bin/codespell#L1
to `#!/usr/bin/env python` and run codespell though.

**Comment by gtmills** [comment]
`pip install --upgrade codespell` 
This is only a problem if I use bin/codespell

**Comment by larsoner** [comment]
You should use `~/.local/bin/codespell` or wherever `pip` installs `codespell`

**Comment by gtmills** [comment]
Yes, that works. 
I will close this issue, thank you for the responses.
