### ISSUE TITLE
Ignoring directories

### ISSUE THREAD

**Issue by neuschaefer** [lucasdemarchi/codespell#60]
Hello,

I would like to ignore everything that's in (or anywhere below) a specific directory. This currently doesn't seem to be supported, though.
Would you mind implementing it?

Thanks for the useful tool!

**Comment by lucasdemarchi** [comment]
A patch for that would be welcome

**Comment by anatol** [comment]
You can utilize `xargs` for this. `find -type f -yourfindparameters | xargs codespell`
