### ISSUE TITLE
Python2 support

### ISSUE THREAD

**Issue by Eric89GXL** [lucasdemarchi/codespell#64]
Would the devs be interested in me adding support for Python2? I've worked on a number of packages with support for Python2 and Python3, so I don't expect it would be too bad.

**Comment by Eric89GXL** [comment]
(I could also take care of #63, at least via a `--returncode` option or so, while I'm at it)

**Comment by Eric89GXL** [comment]
I also kind of hoped #38 (PyPi/pip) would work out of the box, and #60 (ignore directories) would have saved me some pain, so I might try to make time for those, too, if it's welcome.

**Comment by lucasdemarchi** [comment]
@Eric89GXL all of these contributions are welcome. I'm against an option for returncode though. This should be the normal behavior, without needing an option.

**Comment by Eric89GXL** [comment]
Sounds good to me

**Comment by Eric89GXL** [comment]
Are there any unit tests I should use to test it? Or should I write some? I'm concerned about introducing regressions...
