### ISSUE TITLE
There is no ./codespell.py

### ISSUE THREAD

**Issue by jwilk** [lucasdemarchi/codespell#82]
README says:

> Check usage with `./codespell.py -h`

But there is no `./codespell.py` (unless you cd into `bin`, in which case the command doesn't work either).

`codespell.py` was moved from `.` to `bin` in b400e4250d7342b76e361cfcf738da6f65fee035, but I don't understand why. The commit message is enigmatic.

**Comment by Eric89GXL** [comment]
It follows a more standard Python lib pattern to put it in `bin`. Really most people will / should probably now install via `pip` and thus just be able to do `codespell.py` directly

**Comment by gemal** [comment]
```
    copying build/scripts-3.4/codespell.py -> /home/scrutinizer/.pyenv/versions/3.4.1/bin
    changing mode of /home/scrutinizer/.pyenv/versions/3.4.1/bin/codespell.py to 775
```

is this normal? That I cant just run `codespell.py` but it seems only to be able able in `/home/scrutinizer/.pyenv/versions/3.4.1/bin/codespell.py` ?

**Comment by lurch** [comment]
> most people will / should probably now install via `pip` and thus just be able to do `codespell.py` directly

...except now that pypi has been upgraded ( #101 ), `pip` will actually install the executable `codespell` instead of `codespell.py`

**Comment by Eric89GXL** [comment]
Argh, you're right. I guess we should revert to `codespell.py` for backward compatibility reasons

**Comment by Eric89GXL** [comment]
@lucasdemarchi do you agree we should change the name to `bin/codespell.py` instead of `bin/codespell`? I think it's necessary for backward compatibility.

**Comment by lurch** [comment]
Isn't it `better` to have installed commands without the extension? (I assumed this change was deliberate)

**Comment by Eric89GXL** [comment]
Yeah it is better, but I'm worried about backward compatibility. For people who used to do `codespell.py` it won't work anymore. So I'm starting to think we should use the old name.

**Comment by anatol** [comment]
Please keep `codespell` file without file extension. It has been done this way for a long time. The convention has been changed in previous release and that is why we requested reverting it back to `codespell`.

**Comment by Eric89GXL** [comment]
Ahh okay, thanks @anatol

**Comment by jviotti** [comment]
But the problem is that removing `.py` breaks the tool Windows, which relies on extensions to know how to execute a file. Could we have `codespell.py` for Windows, and just `codespell` elsewhere?

**Comment by larsoner** [comment]
Should we just provide both, then?

**Comment by larsoner** [comment]
> Could we have codespell.py for Windows, and just codespell elsewhere?

I guess that's an option, too. I'll look and see what happens with binaries installed from other repos I work on. I know we have command-line utilities and AFAIK we don't do anything special for Windows. It's possible that they have just never worked there, I guess.

**Comment by larsoner** [comment]
I guess that you can use [setuptools](http://setuptools.readthedocs.io/en/latest/setuptools.html#automatic-script-creation) to [take care of it](https://stackoverflow.com/questions/14596057/distributing-python-scripts-without-py-extension). This might be the best/simplest route. Someone want to give it a try?

**Comment by larsoner** [comment]
I have verified locally that `setuptools` does indeed install a `codespell.exe` for Windows so just doing `codespell` works there with #136

**Comment by lurch** [comment]
Woohoo, great to see this issue fixed :+1:   Any chance of a release on PyPi? ;)

**Comment by larsoner** [comment]
Yes that's the next step, I should have time by next week

**Comment by jviotti** [comment]
Has the release been published?

**Comment by larsoner** [comment]
https://pypi.python.org/pypi/codespell/
