### ISSUE TITLE
codespell.py does nothng if [fileN] is not specified

### ISSUE THREAD

**Issue by anatol** [lucasdemarchi/codespell#84]
Previously running `codespell` without file parameter starts the check. Now `codespell.py` does nothing. The behavior should stay the same as before - if file/dir argument is not specefied then current directory should be used as a default parameter.

**Comment by Eric89GXL** [comment]
Can you open a PR to fix it?

Although I'm not sure if that is really the "principle of least surprise" behavior, if it was the default before, I suppose it should stay that way. WDYT @lucasdemarchi?

**Comment by lucasdemarchi** [comment]
We could display the help message or maintain the previous behavior. Doing nothing is the worst. @anatol do you think it would be ok to change the default behavior, requiring an argument? Otherwise let's just go back and do what we were doing.

**Comment by anatol** [comment]
I prefer previous implementation. When I call codespell I expect it checks files in the current context (current directory).

Looking at the `codespell_lib/_codespell.py` it still does the same

```
    (o, args) = parser.parse_args(list(args))

    if not args:
        args.append('.')
```

It should append current directory by default. Maybe recent refactoring changed argument count here?

**Comment by anatol** [comment]
`args` in the code snippet above became `['/usr/bin/codespell.py']`. Before it was an empty array if called like `codespell`. Eric, please fix it.
