### ISSUE TITLE
Makefile is broken

### ISSUE THREAD

**Issue by cinemast** [lucasdemarchi/codespell#85]
The makefile is no longer working, since there is no longer a codespell.py

**Comment by Eric89GXL** [comment]
Can you submit a PR to fix it? Some entries could probably be removed and
others updated.

**Comment by akien-mga** [comment]
Actually most of the Makefile seems obsolete, it should probably be dropped to the profit of setuptools, or rewritten.

**Comment by cinemast** [comment]
I agree. Something that does not work should be removed.

In order for setuptools to work correctly, `bin/codespell.py` should be renamed to `bin/codespell`, since its an executable.

**Comment by Eric89GXL** [comment]
setuptools seems to handle it okay even with the extension. Is it not
working for you on latest master? It's better for backward compatibility
not to change the filename if possible.

**Comment by anatol** [comment]
> not to change the filename if possible

Prior the recent refactoring the name was `codespell`.

**Comment by Eric89GXL** [comment]
Looking back at the repo before the refactoring I see `codespell.py` in the repo:

https://github.com/lucasdemarchi/codespell/tree/4cb7fe36d34784fcb11600834e39c001bee72b2c

Did it get installed as `codespell` when doing the installation step?

**Comment by anatol** [comment]
The rename was done by Makefile rule https://github.com/lucasdemarchi/codespell/blob/4cb7fe36d34784fcb11600834e39c001bee72b2c/Makefile#L16

**Comment by cinemast** [comment]
It does break current operating system packages, and would require lots of otherwise unnecessary patching. Please rename it.

**Comment by cinemast** [comment]
http://python-packaging.readthedocs.io/en/latest/command-line-scripts.html

This link also suggests that executable scripts should drop the file extension

**Comment by Eric89GXL** [comment]
Does #89 look right to you?

**Comment by cinemast** [comment]
I think the Makefile should also be removed in this process. If it doesn't work, its useless and irritating. Otherwise it looks good to me.

**Comment by Eric89GXL** [comment]
@cinemast do you have time to make a PR to remove the Makefile?

**Comment by cinemast** [comment]
Well of course I can, but what is preventing you from simply deleting the Makefile?

**Comment by Eric89GXL** [comment]
I would prefer to make a PR to do it (even if I did it myself) so that people get notified, etc.

**Comment by Eric89GXL** [comment]
(and I haven't contributed to this repo long enough to know what the direct-commit policy is like)
