### ISSUE TITLE
[wishlist] would be great if it is able to generate a patch

### ISSUE THREAD

**Issue by CDLuminate** [lucasdemarchi/codespell#88]
When there're full of typo, a directly generated patch will be great!

**Comment by lucasdemarchi** [comment]
we assume it's on a git repository so you can just see the diff afterwards. Even if it's not in a repository, you can just compare the whole directory with diff... I don't see a point in embedding this into codespell itself.

**Comment by CDLuminate** [comment]
Oops I didn't notice there is a `-w` option for `codespell`, and generating patch with git is indeed a good choice, thanks!
