### ISSUE TITLE
codespell always has an exit value of zero

### ISSUE THREAD

**Issue by elopio** [lucasdemarchi/codespell#94]
Even when there are spelling errors, codespell will exit with a 0. That makes it hard to fail a build step if the spell check fails.

I think it would be nice to exit with a value different than 0 in case of errros. Maybe optional behind a flag to not change the behaviour for existing users.

**Comment by bittorf** [comment]
please send a patch for that.

**Comment by thdot** [comment]
With a simple test it seams to work already in the desired way:
```
$ codespell.py test.txt 
test.txt:0: compatability  ==> compatibility`
$ echo $?
1
```

**Comment by bittorf** [comment]
elopio: please close ticket with 'fixed'
