### ISSUE TITLE
how to ignore directories ?

### ISSUE THREAD

**Issue by luzpaz** [lucasdemarchi/codespell#99]
`codespell.py -d -q 3 --skip="*.po,*.ts,src/3rdParty/*"`
doesn't ignore searching src/3rdParty/

**Comment by luzpaz** [comment]
@lucasdemarchi any insight ?

**Comment by luzpaz** [comment]
if the documentation exists on how to do this.. please direct me to it.. thanks!

**Comment by luzpaz** [comment]
bump

**Comment by lucasdemarchi** [comment]
It's likely a bug in the glob match.

**Comment by luzpaz** [comment]
Anyone able to fix this?

**Comment by luzpaz** [comment]
@lucasdemarchi I ask because I want to use codespell as part of a travis-ci test that runs codespell on commits for spelling mistakes.

**Comment by lucasdemarchi** [comment]
@luzpaz there's a bug in the glob matching right now. I tried here and it seems you can work it around by providing '--skip=src/3rdParty'.  Not the missing '/*' in the end.

**Comment by luzpaz** [comment]
@lucasdemarchi i can't reproduce this workaround.  
Tested on https://github.com/FreeCAD/FreeCAD with
`codespell -d -q 3 --skip="*.po,*.ts,./src/3rdParty"`

**Comment by bartlibert** [comment]
The workaround is not working for me either. Same scenario.

**Comment by lucasdemarchi** [comment]
Have you tried from master? There's a recent PR that went in to address that.

**Comment by luzpaz** [comment]
Please release new minor version so I can test it 🙏 
I have 3 directories I want to skip: 
```
src/CXX 
src/zipios++ 
src/3rdParty 
```

**Comment by larsoner** [comment]
I want to get `#136` in before release.

BTW you can always install latest `master` just by `pip` with `pip install --upgrade git+https://github.com/lucasdemarchi/codespell.git`

**Comment by luzpaz** [comment]
> BTW you can always install latest master just by pip with pip install --upgrade git+https://github.com/lucasdemarchi/codespell.git 

So if I opt for that. Should I first uninstall codespell using my package manager (pacman) and then install via pip3? (since this is python3 based, correct?)  
Also, this is good to know about `--upgrade git+`. perhaps this tidbit of info could be added to the README.md file?

**Comment by luzpaz** [comment]
```
[beast@beast FreeCAD]$ pip3 install --upgrade git+https://github.com/lucasdemarchi/codespell.git
Collecting git+https://github.com/lucasdemarchi/codespell.git
  Cloning https://github.com/lucasdemarchi/codespell.git to /tmp/pip-ouuu_jie-build
Installing collected packages: codespell
  Running setup.py install for codespell ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-ouuu_jie-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-3l4lajda-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib
    creating build/lib/codespell_lib
    copying codespell_lib/_codespell.py -> build/lib/codespell_lib
    copying codespell_lib/__init__.py -> build/lib/codespell_lib
    creating build/lib/codespell_lib/tests
    copying codespell_lib/tests/test_basic.py -> build/lib/codespell_lib/tests
    copying codespell_lib/tests/__init__.py -> build/lib/codespell_lib/tests
    creating build/lib/codespell_lib/data
    copying codespell_lib/data/__init__.py -> build/lib/codespell_lib/data
    running egg_info
    creating codespell.egg-info
    writing codespell.egg-info/PKG-INFO
    writing dependency_links to codespell.egg-info/dependency_links.txt
    writing top-level names to codespell.egg-info/top_level.txt
    writing manifest file 'codespell.egg-info/SOURCES.txt'
    reading manifest file 'codespell.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'codespell.egg-info/SOURCES.txt'
    copying codespell_lib/data/dictionary.txt -> build/lib/codespell_lib/data
    copying codespell_lib/data/linux-kernel.exclude -> build/lib/codespell_lib/data
    running build_scripts
    creating build/scripts-3.6
    copying and adjusting bin/codespell -> build/scripts-3.6
    changing mode of build/scripts-3.6/codespell from 644 to 755
    running install_lib
    creating /usr/lib/python3.6/site-packages/codespell_lib
    error: could not create '/usr/lib/python3.6/site-packages/codespell_lib': Permission denied
    
    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-ouuu_jie-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-3l4lajda-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-ouuu_jie-build/
```
do i need to use `sudo` ?

**Comment by larsoner** [comment]
`sudo` or `pip3 install --user`

> Also, this is good to know about --upgrade git+. perhaps this tidbit of info could be added to the README.md file?

I guess we could, but it's a bit of an advanced option.

**Comment by luzpaz** [comment]
installed with `pip3 install --user --upgrade git+https://github.com/lucasdemarchi/codespell.git`
Output:
```
Collecting git+https://github.com/lucasdemarchi/codespell.git
  Cloning https://github.com/lucasdemarchi/codespell.git to /tmp/pip-scknrxde-build
Installing collected packages: codespell
  Running setup.py install for codespell ... done
Successfully installed codespell-1.11.0.dev0
```
How to I invoke codespell now? It doesn't seem to be in my path

**Comment by larsoner** [comment]
you probably need to add `~/.local/bin` to `PATH`

**Comment by luzpaz** [comment]
Sweet. It works now. Thanks @larsoner 
FYI:
`codespell -d -q 3 --skip="*.po,*.ts,./src/3rdParty,./src/zipios++,./src/CXX"` works!
So we can close this ticket and document it in the README
